name = "notify-hub"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "notify-hub-db"
database_id = "334be7be-90ff-4a6e-a7c9-96c87bd185ae"

[vars]
QUIET_START = "22"
QUIET_END = "7"
TZ_OFFSET = "11"
